[package]
name = "timo_space"
description = "A space to share your sponsorship for the Timo Project."
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
